import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Taxonomy Finder",
  description: "Generated by create next app",
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex flex-col gap-10 p-8 font-[family-name:var(--font-geist-sans)]">
          <div className="flex flex-row items-center gap-4">
            <Link href="/"><h1>Taxonomy <span className="font-bold">Finder</span></h1></Link>
          </div>
          <div>
            {children}
          </div>
        </div>

        <section>
          <div className='air air1'></div>
          <div className='air air2'></div>
          <div className='air air3'></div>
          <div className='air air4'></div>
        </section>
      </body>
    </html>
  );
}
